export const LANGUAGES = [
  { ar: "اللغة العربية" },
  { bn: "বাংলা" },
  { cn: "中国人" },
  { de: "Deutsche" },
  { en: "English" },
  { es: "Español" },
  { fr: "Français" },
  { gu: "ગુજરાતી" },
  { hi: "हिंदी" },
  { id: "Indonesian" },
  { it: "Italiano" },
  { ja: "日本語" },
  { kn: "ಕನ್ನಡ" },
  { ko: "한국어" },
  { ky: "Кыргызча" },
  { la: "Latine" },
  { ms: "Melayu" },
  { ml: "മലയാളം" },
  { mr: "मराठी" },
  { ne: "नेपाली" },
  { nl: "Deutsch" },
  { no: "norsk" },
  { pa: "ਪੰਜਾਬੀ" },
  { fa: "فارسی" },
  { pt: "Português" },
  { ru: "Pусский" },
  { sa: "संस्कृत" },
  { sv: "svenska" },
  { ta: "தமிழ்" },
  { te: "తెలుగు" },
  { th: "ภาษาไทย" },
  { tr: "Türk" },
  { uk: "Український" },
  { ur: "اردو" },
  { uz: "O'zbek" },
  { vi: "tiếng Việt" },
  { mt: "multiple" },
  { "": "Other" },
];

export const CATEGORIES = [
  "🦁 Animals & Pets",
  "🎎 Anime",
  "🎨 Art & Paintings",
  "📚 Books",
  "🏎 Cars",
  "💼 Career",
  "💃🏼 Celebrity",
  "👨‍👨‍👧‍👦 Community",
  "⛓ Cryptocurrency",
  "👩‍❤️‍👨 Dating",
  "🎓 Educational",
  "🎭 Entertainment",
  "🧐 Facts",
  "💰 Finance",
  "😂 Funny",
  "🎮 Gaming",
  "🃏 GIFs",
  "💻 Hacking",
  "👩‍⚕️ Health",
  "🧛 Horror",
  "🧠 Knowledge",
  "🔮 Life Hacks",
  "💅🏻 Lifestyle",
  "😂 Memes",
  "🎬 Movies",
  "🌞 Motivational",
  "🏕 Nature",
  "📰 News",
  "🤵🏻 Political",
  "🙋🏼 Personal",
  "🖼 Photography",
  "🏋️ Productive",
  "💻 Programming",
  "🔗 Promotion",
  "🌐 Proxy",
  "🗺 Regional",
  "🥰 Relationship",
  "🔬 Science",
  "🎧 Song",
  "📱 Social",
  "🛒 Shopping",
  "🕉 Spiritual",
  "🏀 Sports",
  "🚀 Startup",
  "🏙 Stickers",
  "📈 Stocks",
  "🤴 Stories",
  "📲 Technical",
  "📨 Telegram",
  "💭 Thoughts",
  "💫 Tips & tricks",
  "✈️ Travelling",
  "🧵 Utility",
  "📹 Videos",
  "🎲 Others",
  "",
];
